### PR TITLE
Added Custom Color Scheme functionality

### PR DESCRIPTION
**Pull request by whoislyuboanyway**

### CODE REVIEW

**Review by shoheiyokoyama — APPROVED** [review]

**Comment by shoheiyokoyama** [comment]
Thank you @whoislyuboanyway

**Comment by whoislyuboanyway** [comment]
Yeah, no problem :) Sorry for the messy commits, but I was pressured by the time :)

**Comment by shoheiyokoyama** [comment]
@whoislyuboanyway 
I just released version 1.2.7

https://cocoapods.org/pods/Koyomi

**Comment by whoislyuboanyway** [comment]
You should update the description because it doesn't match the README (the stuff I added :) )

**Pull request merged**
