### PR TITLE
Some useful features

### PR DESCRIPTION
**Pull request by EvilClay**
- added ability to define selection colours for individual cells via delegate
- added ability to define font for individual cells via delegate (can be used for example to display current day in bold)
- added ability to define the circle size for selection (from hardcoded 75%)

### CODE REVIEW

**Comment by shoheiyokoyama** [comment]
@EvilClay 
Please update README

**Comment by EvilClay** [comment]
@shoheiyokoyama 
Done

**Comment by shoheiyokoyama** [comment]
@EvilClay 
Thank you for contribution 😄

**Comment by shoheiyokoyama** [comment]
@EvilClay 
I have just finished to release version `1.2.3`🎊.
I’m looking forward to your contribution in the near future.
[Koyomi 1.2.3](https://cocoapods.org/pods/Koyomi)

**Pull request merged**
